//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

// MARK: - Interactor

protocol ___VARIABLE_productName:identifier___InteractorProtocol: class {
    var presenter: ___VARIABLE_productName:identifier___PresenterProtocol? { get set }
}

class ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorProtocol {

    weak var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?
}
